version: "3.3"
services:
  dnsmasq-service-0:
    build: .
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq-config/dnsmasq-china-list/accelerated-domains.china.conf:/etc/dnsmasq.d/accelerated-domains.china.conf
      - ./dnsmasq-config/dnsmasq-china-list/apple.china.conf:/etc/dnsmasq.d/apple.china.conf
      - ./dnsmasq-config/dnsmasq-china-list/google.china.conf:/etc/dnsmasq.d/google.china.conf
    extra_hosts:
       - "outside:10.7.32.25"
  dnsmasq-service-1:
    build: .
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq-config/dnsmasq-china-list/accelerated-domains.china.conf:/etc/dnsmasq.d/accelerated-domains.china.conf
      - ./dnsmasq-config/dnsmasq-china-list/apple.china.conf:/etc/dnsmasq.d/apple.china.conf
      - ./dnsmasq-config/dnsmasq-china-list/google.china.conf:/etc/dnsmasq.d/google.china.conf
    extra_hosts:
       - "outside:10.7.32.26"
